export interface ProductState {
  id?: string; // optional because when creating a new product, the ID will be generated by Firestore
  title: string;
  price: number;
  category: string;
  description: string;
  image: string;
  rating: {
    rate: number;
  };
}
